.TH serveur 1 "November 29, 2017" "Version 0.1" "USER COMMANDS"
.DT SERVEUR 1
.SH NOM
serveur \- lance un serveur pouvant stocker des hash et des IP
.SH SYNOPSYS
.B serveur 
IPV6 PORT [IPV6_SERVER PORT_SERVER]
.SH DESCRIPTION
Cree un serveur permettant d'associer des ip a un hash recus par un client ou
par un autre serveur. Il permet aussi d'envoyer ses IPs et ses hash a la demande. Ce serveur a pour adresse ip l'
.B IP
donnee en parametre et travail sur le port
.B PORT.
Il peut aussi se connecter a un autre serveur ayant pour adresse
.B IPV6_SERVER
et travaillant sur le port
.B PORT_SERVER.
.SH PARAMETRES
.TP 
.B IPV6
Le serveur prendra comme adresse IPv6 celle renseignee, ou l'adresse IPv6 de l'hote si un c'est un nom de domaine qui est donne
.TP 
.B PORT
Numero de port sur lequel le serveur doit envoyer et recevoir des messages
.TP 
.B IPV6_SERVER
Si une autre adresse IPv6 ou un hote est renseigne, alors le serveur ce connectera au serveur possedant cette adresse IPv6. Si une nouvelle adresse est donnee, un numéro de port doit aussi etre renseigne pour etre associe a cette adresse 
.TP
.B PORT_SERVER
En renseignant une autre adresse IPv6, il est obligatoire de donnee un nouveau numero de port. Ce dernier sera assigne à l'adresse IPv6 du serveur auquel nous voulons connecter notre serveur
.SH EXEMPLES
.TP
Lance un serveur ayant comme ip celle de google.fr et le port 6719:

.B serveur
google.fr 6719
.PP
.TP
Lance un serveur ayant comme ip l'ip local et le port 8000 en se connectant au serveur precedement cree:

.B serveur 
ip6-localhost 8000 google.fr 6719
.PP
Une fois les deux serveurs connectes entre eux, le serveur ayant comme 
adresse IPv6 google.fr va envoyer toutes sa table de hash au serveur ayant 
comme adresse IPv6 ip6-localhost
.SH STATUS DE SORTIE
.TP 
S_INIT_TABLE
Initialisation de la table
.TP 
S_CONNEXION_SERVER
Connexion d'un serveur a un autre
.TP 
S_UNKNOWN_COMMAND
Commande non connu (PUT, GET, ...)
.TP 
S_NB_ARGS
Nombre d'arguments non valide
.TP 
S_NUM_PORT_SERVER
Numero de port pour la creation du serveur incorrect
.TP 
S_NUM_PORT_CONNEXION
Numero de port pour la connexion a un autre serveur incorrect
.TP
INIT_SOCKET
Lors de l'initialisation d'un socket
.TP
RECEIVE
Lors de la reception d'un message
.TP
SEND      
Lors de l'envoi d'un message
.TP
FORMAT       
La chaine utilisee pour cree le format de donnee est trop grande
.TP
ADRESSE
L'adresse IPv6 ou l'hote fourni en paramètre ne fournisse pas d'adresse IPv6 valide
.SH AUTEUR
Ecrit par Florian GUILLEMEAU & Sylvain LANGENBRONN
.SH VOIR AUSSI
client(1)
