.TH serveur 1 "November 29, 2017" "Version 0.1" "USER COMMANDS"
.DT SERVEUR 1
.SH NOM
serveur \- lance un serveur pouvant stocker des hash et des IP
.SH SYNOPSYS
.B serveur 
.I hote_ipv6 port 
.B [
.I h_ip6_connect port_connect
.B ]
.SH DESCRIPTION
Cree un serveur permettant d'associer des ip a un hash reçus par un client ou
par un autre serveur. Il permet aussi d'envoyer ses ip et ses hash a d'autres
serveurs.
.SH PARAMETRES
.IP hote_ipv6
Le serveur prendra comme adresse IPv6 celle renseignee, ou l'adresse IPv6 de l'hote si un c'est un nom de domaine qui est donne
.IP port
Numero de port sur lequel le serveur doit envoyer et recevoir des messages
.IP h_ip6_connect
Si une autre adresse IPv6 ou un hote est renseigne, alors le serveur ce connectera au serveur possedant cette adresse IPv6. Si une nouvelle adresse est donnee, un numéro de port doit aussi etre renseigne pour etre associe a cette adresse
.IP port_connect
En renseignant une autre adresse IPv6, il est obligatoire de donnee un nouveau numero de port. Ce dernier sera assigne à l'adresse IPv6 du serveur auquel nous voulons connecter notre serveur
.SH Auteur
Ecrit par Sylvain Langenbronn
.SH VOIR AUSSI
client
